/**
 * HTML Sanitization utility for dashboard content
 *
 * This module provides security-focused HTML sanitization to prevent XSS attacks
 * while preserving the layout and styling generated by Claude.
 *
 * Note: DOMPurify is used client-side. For server-side rendering,
 * we use a simple allowlist-based approach.
 */

// Allowed HTML tags - covers semantic HTML and common layout elements
// Note: header, footer, nav are intentionally EXCLUDED to prevent AI-generated
// content from conflicting with the application shell
const ALLOWED_TAGS = new Set([
  // Document structure (stripped by sanitizer, but allowed for parsing)
  'html', 'head', 'body',
  // Semantic sections (header, footer, nav excluded - provided by app shell)
  'main', 'section', 'article', 'aside',
  // Headings
  'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
  // Text content
  'p', 'span', 'div', 'blockquote', 'pre', 'code',
  'strong', 'em', 'b', 'i', 'u', 's', 'small', 'mark', 'sub', 'sup',
  // Lists
  'ul', 'ol', 'li', 'dl', 'dt', 'dd',
  // Tables
  'table', 'thead', 'tbody', 'tfoot', 'tr', 'th', 'td', 'caption', 'colgroup', 'col',
  // Media
  'img', 'figure', 'figcaption', 'picture', 'source', 'svg', 'path', 'circle', 'rect', 'line', 'polygon', 'g',
  // Interactive (safe ones)
  'a', 'button',
  // Form elements (display only)
  'label', 'output', 'meter', 'progress',
  // Other
  'br', 'hr', 'wbr',
  // Data attributes container
  'data',
]);

// Allowed attributes
const ALLOWED_ATTRS = new Set([
  // Global attributes
  'id', 'class', 'style', 'title', 'lang', 'dir',
  // Data attributes (handled separately with data-* prefix)
  'data-chart', 'data-title', 'data-type',
  // Links
  'href', 'target', 'rel',
  // Images
  'src', 'alt', 'width', 'height', 'loading',
  // Tables
  'colspan', 'rowspan', 'scope',
  // SVG attributes
  'viewBox', 'fill', 'stroke', 'stroke-width', 'd', 'cx', 'cy', 'r', 'x', 'y', 'x1', 'y1', 'x2', 'y2', 'points', 'transform',
  // ARIA accessibility
  'role', 'aria-label', 'aria-labelledby', 'aria-describedby', 'aria-hidden',
]);

// Dangerous patterns to remove
const DANGEROUS_PATTERNS = [
  // Script injection
  /<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,
  // Event handlers
  /\bon\w+\s*=/gi,
  // JavaScript URLs
  /javascript:/gi,
  // Data URLs with scripts
  /data:\s*text\/html/gi,
  // VBScript
  /vbscript:/gi,
  // Expression (IE CSS)
  /expression\s*\(/gi,
  // Import
  /@import/gi,
  // Behavior (IE CSS)
  /behavior\s*:/gi,
  // Binding (Mozilla CSS)
  /-moz-binding/gi,
];

// Patterns for AI-generated content that should be stripped
// These elements conflict with the application shell
const AI_SHELL_PATTERNS = [
  // Remove <header> elements entirely (the app provides its own header)
  /<header\b[^>]*>[\s\S]*?<\/header>/gi,
  // Remove <nav> elements (navigation is provided by the app)
  /<nav\b[^>]*>[\s\S]*?<\/nav>/gi,
  // Remove <footer> elements (footer is provided by the app for public views)
  /<footer\b[^>]*>[\s\S]*?<\/footer>/gi,
];

// CSS patterns that could break the app shell layout
const DANGEROUS_CSS_PATTERNS = [
  // Fixed positioning that covers the viewport
  /position\s*:\s*fixed/gi,
  // Absolute positioning with top: 0 (likely a header)
  /position\s*:\s*absolute[^;]*;\s*top\s*:\s*0/gi,
];

/**
 * Sanitize HTML content for safe rendering
 * This is a server-side compatible sanitization function
 */
export function sanitizeHTML(html: string): string {
  let sanitized = html;

  // Remove dangerous patterns first
  for (const pattern of DANGEROUS_PATTERNS) {
    sanitized = sanitized.replace(pattern, '');
  }

  // Remove AI-generated shell elements (header, nav, footer)
  // These conflict with the application shell
  for (const pattern of AI_SHELL_PATTERNS) {
    sanitized = sanitized.replace(pattern, '');
  }

  // Remove dangerous CSS patterns that could break the app layout
  // We replace position: fixed with position: relative to preserve layout intent
  for (const pattern of DANGEROUS_CSS_PATTERNS) {
    sanitized = sanitized.replace(pattern, 'position: relative');
  }

  // Remove comments that might contain malicious content
  sanitized = sanitized.replace(/<!--[\s\S]*?-->/g, '');

  // Remove any remaining script tags (belt and suspenders)
  sanitized = sanitized.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, '');

  // Remove any remaining event handlers
  sanitized = sanitized.replace(/\s+on\w+\s*=\s*["'][^"']*["']/gi, '');
  sanitized = sanitized.replace(/\s+on\w+\s*=\s*[^\s>]+/gi, '');

  return sanitized;
}

/**
 * Client-side sanitization using DOMPurify
 * Use this when running in the browser for more thorough sanitization
 */
export async function sanitizeHTMLClient(html: string): Promise<string> {
  if (typeof window === 'undefined') {
    // Server-side: use basic sanitization
    return sanitizeHTML(html);
  }

  // Client-side: use DOMPurify
  const DOMPurify = (await import('dompurify')).default;

  return DOMPurify.sanitize(html, {
    ALLOWED_TAGS: Array.from(ALLOWED_TAGS),
    ALLOWED_ATTR: Array.from(ALLOWED_ATTRS),
    ALLOW_DATA_ATTR: true,
    ALLOW_UNKNOWN_PROTOCOLS: false,
    SANITIZE_DOM: true,
  });
}

/**
 * Extract chart placeholder IDs from HTML
 */
export function extractChartPlaceholders(html: string): string[] {
  const placeholders: string[] = [];
  const regex = /data-chart=["']([^"']+)["']/g;
  let match;

  while ((match = regex.exec(html)) !== null) {
    placeholders.push(match[1]);
  }

  return placeholders;
}

/**
 * Validate that all chart placeholders have corresponding configs
 */
export function validateChartConfigs(
  html: string,
  charts: Record<string, unknown>
): { valid: boolean; missing: string[] } {
  const placeholders = extractChartPlaceholders(html);
  const chartIds = new Set(Object.keys(charts));
  const missing = placeholders.filter(id => !chartIds.has(id));

  return {
    valid: missing.length === 0,
    missing,
  };
}
